trigger:
- dev

variables:
- group: NuGet

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byBuildNumber'
    verbosityPack: 'Normal'

#- task: NuGetToolInstaller@1
#  displayName: 'Install NuGet'
#- script: nuget push $(Build.ArtifactStagingDirectory)\$(projectName).*.nupkg -Source $(nugetSource) -ApiKey $(NuGet.nuget-org-apikey) -SkipDuplicate -NoSymbols
#  displayName: 'Push to NuGet.org'
    
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'