trigger: none
pr: 
- master

variables:
- name: BuildConfiguration
  value: 'release'
- name: packagesInfoPath
  value: "./PackagesInfo.proj"

pool:
  vmImage: windows-latest

steps:

- powershell: |

   $xml = [Xml] (Get-Content $(packagesInfoPath))
   $version = $xml.Project.PropertyGroup.Version
   $versionChunks = $version.Split(".")[0..2]
   
   echo "Package version is $version"

   echo "##vso[task.setvariable variable=majorVersion]$($versionChunks[0])"
   echo "##vso[task.setvariable variable=minorVersion]$($versionChunks[1])"
   echo "##vso[task.setvariable variable=patchVersion]$($versionChunks[2])"
  displayName: 'Get packages version'

- task: UseDotNet@2
  displayName: "Use .NET Sdk"
  inputs:
    version: 6.0.x

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '**/*.sln'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'