trigger: none
pr: none

variables:
- group: NuGet
- name: nugetSource
  value: 'https://api.nuget.org/v3/index.json'
- name: BuildConfiguration
  value: 'release'
- name: packagesInfoPath
  value: "./PackagesInfo.proj"

pool:
  vmImage: windows-latest

steps:

- powershell: |

   $xml = [Xml] (Get-Content $(packagesInfoPath))
   $version = $xml.Project.PropertyGroup.Version
   $versionChunks = $version.Split(".")[0..2]
   
   echo "Package version is $version"

   echo "##vso[task.setvariable variable=majorVersion]$($versionChunks[0])"
   echo "##vso[task.setvariable variable=minorVersion]$($versionChunks[1])"
   echo "##vso[task.setvariable variable=patchVersion]$($versionChunks[2])"
  displayName: 'Get packages version'

- task: UseDotNet@2
  displayName: "Use .NET Sdk"
  inputs:
    version: 6.0.x

- task: DotNetCoreCLI@2
  displayName: 'dotnet build and pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    verbosityPack: 'Minimal'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(majorVersion)'
    minorVersion: '$(minorVersion)'
    patchVersion: '$(patchVersion)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org devTrevi'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'